image:
  repository: eu.gcr.io/gardener-project/gardener/kupid
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

logging:
  level: info

resources:
  requests:
    cpu: 100m
    memory: 64M
  limits:
    cpu: 200m
    memory: 256M

vpa:
  enabled: true
  minAllowed:
    cpu: 100m
    memory: 64M
  updatePolicy:
    updateMode: "Auto"
 
webhookConfig:
  serverPort: 9443
  timeoutSeconds: 30