apiVersion: kupid.gardener.cloud/v1alpha1
kind: ClusterPodSchedulingPolicy
metadata:
  name: cpsp-node-selector
spec:
  namespaceSelector: {}
  podSelector:
    matchLabels:
      app: etcd-statefulset
      role: main
  nodeSelector:
    worker-pool.gardener.cloud/dedicated-for: etcd