apiVersion: kupid.gardener.cloud/v1alpha1
kind: ClusterPodSchedulingPolicy
metadata:
  name: cpsp-node-selector-tolerations
spec:
  namespaceSelector: {}
  podSelector:
    matchLabels:
      app: etcd-statefulset
      role: events
  nodeSelector:
    worker-pool.gardener.cloud/dedicated-for: etcd
  tolerations:
  - key: worker-pool.gardener.cloud/dedicated-for
    operator: Equal
    value: etcd
    effect: NoSchedule
