apiVersion: kupid.gardener.cloud/v1alpha1
kind: PodSchedulingPolicy
metadata:
  name: psp-pod-affinity-anti-affinity
spec:
  podSelector:
    matchLabels:
      app: etcd-statefulset
      role: main
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app: etcd-statefulset
            role: main
        topologyKey: kubernetes.io/hostname
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: NotIn
              values:
              - etcd-statefulset
            - key: role
              operator: NotIn
              values:
              - main
          topologyKey: kubernetes.io/hostname
      
