apiVersion: kupid.gardener.cloud/v1alpha1
kind: PodSchedulingPolicy
metadata:
  name: psp-tolerations
spec:
  podSelector:
    matchLabels:
      app: etcd-statefulset
      role: main
  tolerations:
  - key: worker-pool.gardener.cloud/dedicated-for
    operator: Equal
    value: etcd
    effect: NoSchedule