apiVersion: kupid.gardener.cloud/v1alpha1
kind: PodSchedulingPolicy
metadata:
  name: psp-node-selector
spec:
  podSelector:
    matchLabels:
      app: etcd-statefulset
      role: main
  nodeSelector:
    worker-pool.gardener.cloud/dedicated-for: etcd