apiVersion: kupid.gardener.cloud/v1alpha1
kind: PodSchedulingPolicy
metadata:
  name: psp-node-name
spec:
  podSelector:
    matchLabels:
      app: etcd-statefulset
      role: main
  nodeName: node-1
    