apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
{{-  if .Values.ignoreResources }}
  annotations:
    resources.gardener.cloud/ignore: "true"
{{- end }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
{{ include "labels" . | indent 6 }}
  ports:
  - port: 443
    name: webhook-server
    protocol: TCP
    targetPort: {{ .Values.webhookConfig.serverPort }}
  - port: {{ .Values.metricsPort }}
    name: metrics
    protocol: TCP
    targetPort: {{ .Values.metricsPort }}
